// ============================================================
// 12_driver_airport_sync.gs — Driver Airport SSOT Sync V3
// Fix code 21000: normalize -> validate -> dedupe -> conflict log -> bulk upsert.
// LOCAL WORKING COPY. NO DEPLOY.
// ============================================================
const DRIVER_AIRPORT_SHEET_ID=PropertiesService.getScriptProperties().getProperty('DRIVER_AIRPORT_SHEET_ID')||'1FEZxyHPx_GCQKw92hLSf6QxxkXgZn5R1sRswOYM_Tlc';
const DRIVER_AIRPORT_TABS=['ID Rifim Airport Soeta','ID Rifim Airport Batam','ID Rifim Airport Jambi','ID Rifim Airport Balikpapan','ID Rifim Airport Manado','ID Rifim Airport Pekanbaru','ID Rifim Airport Makassar'];
function getDriverAirportSpreadsheet_(){return SpreadsheetApp.openById(DRIVER_AIRPORT_SHEET_ID)}
function _drvNormId_(v){return String(v||'').trim()}
function _drvWinnerScore_(r,existing){var score=0;if(r.name)score+=3;if(r.branch_id)score+=2;if(existing&&existing.branch_id&&r.branch_id===existing.branch_id)score+=10;score+=(100000-r.row_order)/1000000;return score}
function _drvDedupeSource_(raw,existingMap){var byId={},warnings=[];raw.forEach(function(r){var old=byId[r.driver_id];if(!old){byId[r.driver_id]=r;return}var existing=existingMap[r.driver_id],winner=_drvWinnerScore_(r,existing)>_drvWinnerScore_(old,existing)?r:old,loser=winner===r?old:r;byId[r.driver_id]=winner;warnings.push('Duplicate source driver_id='+r.driver_id+' winner='+winner.tab+'#'+winner.row_num+' loser='+loser.tab+'#'+loser.row_num+'; deterministic winner, tidak merge berdasarkan nama')});return {rows:Object.keys(byId).map(function(k){return byId[k]}),warnings:warnings}}
function _drvDedupeProfiles_(rows){var byId={},byStaff={},out=[],warnings=[];rows.forEach(function(r){if(byId[r.id]){warnings.push('Duplicate profile auth id '+r.id+' staff '+r.staff_id+' — skip duplicate');return}if(byStaff[r.staff_id]){warnings.push('Duplicate profile staff_id '+r.staff_id+' auth '+byStaff[r.staff_id].id+' vs '+r.id+' — first valid wins');return}byId[r.id]=r;byStaff[r.staff_id]=r;out.push(r)});return {rows:out,warnings:warnings}}
function syncDriverAirportFromSSOT(){var t0=Date.now(),upserted=0,deactivated=0,skippedNonSsot=0,errors=0,authNew=0,authCached=0,authFailed=0,warnings=[];try{var ss=getDriverAirportSpreadsheet_(),branchMap=kpiBranchMap_(),now=new Date().toISOString();var existingProfiles=callSupabase('user_profiles?role=eq.driver&source=eq.ssot_driver_airport&select=id,staff_id,driver_id,branch_id&limit=5000')||[],provisioned={};existingProfiles.forEach(function(p){if(p.staff_id)provisioned[p.staff_id]=p});var existingDrivers=callSupabase('raos_drivers?select=id,driver_id,source,branch_id&limit=10000')||[],existingMap={};existingDrivers.forEach(function(d){if(d.driver_id)existingMap[d.driver_id]=d});
  var raw=[],order=0,available=ss.getSheets().map(function(s){return s.getName()});DRIVER_AIRPORT_TABS.forEach(function(tab){var sh=ss.getSheetByName(tab);if(!sh){warnings.push('Tab '+tab+' tidak ditemukan. Tersedia: '+available.join(', '));return}var branchId=branchMap[tab]||null;if(!branchId)warnings.push('Branch '+tab+' tidak ada di branches');sh.getDataRange().getValues().slice(1).forEach(function(row,i){var id=_drvNormId_(row[1]),name=String(row[2]||'').trim();if(!id)return;order++;if(!/^\d{6,}$/.test(id)){warnings.push(tab+'#'+(i+2)+' driver_id invalid '+id+' — skip');return}var ex=existingMap[id];if(ex&&ex.source!=='ssot_driver_airport'){skippedNonSsot++;warnings.push('driver_id '+id+' source='+ex.source+' tidak ditimpa');return}raw.push({driver_id:id,name:name,branch_id:(ex&&ex.branch_id)||branchId,tab:tab,row_num:i+2,row_order:order})})});
  var ded=_drvDedupeSource_(raw,existingMap);warnings=warnings.concat(ded.warnings);var rows=ded.rows,seen=rows.map(function(r){return r.driver_id}),payload=rows.map(function(r){return {driver_id:r.driver_id,name:r.name,branch_id:r.branch_id,source:'ssot_driver_airport',driver_type:'airport',is_active:true,ssot_synced_at:now}});var CHUNK=400;for(var i=0;i<payload.length;i+=CHUNK){var ch=payload.slice(i,i+CHUNK);try{_raosDriverBulkUpsert_(ch);upserted+=ch.length}catch(e){errors++;warnings.push('Bulk raos_drivers chunk '+i+': '+e.message)}}
  var need=rows.filter(function(r){if(provisioned[r.driver_id]){authCached++;return false}return true});if(need.length){var uuidMap={},ids=need.map(function(d){return d.driver_id});for(i=0;i<ids.length;i+=100){var list=ids.slice(i,i+100).map(encodeURIComponent).join(','),rr=callSupabase('raos_drivers?driver_id=in.('+list+')&select=id,driver_id')||[];rr.forEach(function(x){uuidMap[x.driver_id]=x.id})}
    var reqs=need.map(function(d){return {driver:d,request:{url:CONFIG.SUPABASE_URL+'/auth/v1/admin/users',method:'post',contentType:'application/json',headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:'Bearer '+CONFIG.SUPABASE_KEY},payload:JSON.stringify({email:d.driver_id+'@driver.rifim.local',password:d.driver_id,email_confirm:true,user_metadata:{full_name:d.name,driver_id_text:d.driver_id,role:'driver'}}),muteHttpExceptions:true}}}),profile=[];for(i=0;i<reqs.length;i+=50){var batch=reqs.slice(i,i+50),responses=UrlFetchApp.fetchAll(batch.map(function(b){return b.request}));for(var j=0;j<batch.length;j++){var d=batch[j].driver,res=responses[j],code=res.getResponseCode(),authId=null;if(code>=200&&code<300){try{authId=JSON.parse(res.getContentText()).id}catch(_){}}else if(code===422||res.getContentText().indexOf('already')>=0){try{authId=callSupabase('rpc/get_auth_user_id_by_email','POST',{p_email:d.driver_id+'@driver.rifim.local'});if(Array.isArray(authId))authId=authId[0]}catch(_){}}if(!authId||!uuidMap[d.driver_id]){authFailed++;warnings.push('Auth/driver UUID gagal '+d.driver_id+' HTTP '+code);continue}profile.push({id:authId,staff_id:d.driver_id,full_name:d.name,role:'driver',driver_id:uuidMap[d.driver_id],branch_id:d.branch_id,source:'ssot_driver_airport',ssot_synced_at:now,is_active:true});authNew++;}}
    var pd=_drvDedupeProfiles_(profile);warnings=warnings.concat(pd.warnings);for(i=0;i<pd.rows.length;i+=CHUNK){try{_raosUserProfilesBulkUpsert_(pd.rows.slice(i,i+CHUNK))}catch(e){errors++;warnings.push('Bulk user_profiles chunk '+i+': '+e.message)}}}
  var stale=existingDrivers.filter(function(d){return d.source==='ssot_driver_airport'&&seen.indexOf(d.driver_id)<0}).map(function(d){return d.driver_id});for(i=0;i<stale.length;i+=100){var sl=stale.slice(i,i+100);try{callSupabase('raos_drivers?driver_id=in.('+sl.map(encodeURIComponent).join(',')+')','PATCH',{is_active:false,ssot_synced_at:now});deactivated+=sl.length}catch(e){errors++;warnings.push('Deactivate: '+e.message)}}
  warnings.slice(0,50).forEach(function(w){try{logSistem('warning','syncDriverAirportFromSSOT','warning',w)}catch(_){}});var elapsed=((Date.now()-t0)/1000).toFixed(1),status=errors?'warning':(warnings.length?'warning':'success'),summary=upserted+' upsert, '+deactivated+' nonaktif, '+skippedNonSsot+' skip-non-ssot, '+authNew+' auth baru, '+authCached+' auth cached, '+authFailed+' auth failed, '+ded.warnings.length+' duplicate source, '+errors+' error, '+elapsed+'s';logSistem('sync','syncDriverAirportFromSSOT',status,summary);return {upserted:upserted,deactivated:deactivated,skippedNonSsot:skippedNonSsot,authProvisionedNew:authNew,authCached:authCached,authFailed:authFailed,duplicates:ded.warnings.length,errors:errors,warnings:warnings.length,warning_details:warnings.slice(0,20),elapsed_s:Number(elapsed)};}catch(e){try{logSistem('error','syncDriverAirportFromSSOT','error',e.message||String(e))}catch(_){}throw e}}
function _raosDriverBulkUpsert_(rows){if(!rows.length)return;var unique={};rows.forEach(function(r){if(unique[r.driver_id])throw new Error('internal dedupe guard: duplicate driver_id '+r.driver_id);unique[r.driver_id]=true});var res=UrlFetchApp.fetch(CONFIG.SUPABASE_URL+'/rest/v1/raos_drivers?on_conflict=driver_id',{method:'POST',headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:'Bearer '+CONFIG.SUPABASE_KEY,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},payload:JSON.stringify(rows),muteHttpExceptions:true});if(res.getResponseCode()>=400)throw new Error('HTTP '+res.getResponseCode()+': '+res.getContentText().substring(0,500))}
function _raosUserProfilesBulkUpsert_(rows){if(!rows.length)return;var ids={},staff={};rows.forEach(function(r){if(ids[r.id])throw new Error('internal dedupe guard duplicate user_profiles.id '+r.id);if(staff[r.staff_id])throw new Error('internal dedupe guard duplicate user_profiles.staff_id '+r.staff_id);ids[r.id]=true;staff[r.staff_id]=true});var res=UrlFetchApp.fetch(CONFIG.SUPABASE_URL+'/rest/v1/user_profiles?on_conflict=id',{method:'POST',headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:'Bearer '+CONFIG.SUPABASE_KEY,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},payload:JSON.stringify(rows),muteHttpExceptions:true});if(res.getResponseCode()>=400)throw new Error('HTTP '+res.getResponseCode()+': '+res.getContentText().substring(0,500))}
// Recovery function intentionally kept backend-compatible. UI labels it RECOVERY / OPTIONAL.
function forceRefreshDriverAirportAuth(){var t0=Date.now(),refreshed=0,skippedNoAuth=0,failed=0;var profiles=callSupabase('user_profiles?role=eq.driver&source=eq.ssot_driver_airport&select=id,staff_id&limit=5000')||[],auth={};profiles.forEach(function(p){if(p.staff_id)auth[p.staff_id]=p.id});var targets=[],seen={};var ss=getDriverAirportSpreadsheet_();DRIVER_AIRPORT_TABS.forEach(function(tab){var sh=ss.getSheetByName(tab);if(!sh)return;sh.getDataRange().getValues().slice(1).forEach(function(row){var id=_drvNormId_(row[1]);if(!/^\d{6,}$/.test(id)||seen[id])return;seen[id]=true;if(!auth[id]){skippedNoAuth++;return}targets.push({driverId:id,authId:auth[id]})})});for(var i=0;i<targets.length;i+=50){var b=targets.slice(i,i+50),resp=UrlFetchApp.fetchAll(b.map(function(t){return {url:CONFIG.SUPABASE_URL+'/auth/v1/admin/users/'+t.authId,method:'put',contentType:'application/json',headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:'Bearer '+CONFIG.SUPABASE_KEY},payload:JSON.stringify({password:t.driverId}),muteHttpExceptions:true}}));resp.forEach(function(r,j){if(r.getResponseCode()>=200&&r.getResponseCode()<300)refreshed++;else{failed++;try{logSistem('error','forceRefreshDriverAirportAuth','error',b[j].driverId+' HTTP '+r.getResponseCode())}catch(_){}}})}var elapsed=((Date.now()-t0)/1000).toFixed(1);logSistem('recovery','forceRefreshDriverAirportAuth',failed?'warning':'success','refreshed='+refreshed+' skipped='+skippedNoAuth+' failed='+failed+' '+elapsed+'s');return {refreshed:refreshed,skippedNoAuth:skippedNoAuth,failed:failed,errors:failed,elapsed_s:Number(elapsed)}}
