// ============================================================
// 13_staff_sync.gs — Staff SSOT Sync V4 Lifecycle + Identity Hardening
// Identity: canonical staff_id + email + Auth UUID. Never merge by name.
// Lifecycle: MASTER DATA STAFF `Status Aktif` is canonical.
// ============================================================
const MASTER_STAFF_SHEET_ID=PropertiesService.getScriptProperties().getProperty('MASTER_STAFF_SHEET_ID')||'1fcraq3QHqIaD-13Ebzt6stT9aA6j_loTXeAtpNX12kw';const MASTER_STAFF_TAB_NAME='MASTER DATA STAFF';const SYSTEM_ROLE_VALUES=['staff','koordinator','admin','management','direksi','driver_manager','driver'];const SKIP_CABANG_SYNC=[];const GEOFENCE_EXEMPT_STAFF_PATTERNS=[/^gusril/i,/^hadityawarman/i];
function isStaffGeofenceExempt_(n){var s=String(n||'').trim();return GEOFENCE_EXEMPT_STAFF_PATTERNS.some(function(re){return re.test(s)})}
function getMasterStaffSheet_(){var ss=SpreadsheetApp.openById(MASTER_STAFF_SHEET_ID),sh=ss.getSheetByName(MASTER_STAFF_TAB_NAME);if(!sh)throw new Error('Tab '+MASTER_STAFF_TAB_NAME+' tidak ditemukan');return sh}
function mapJabatanToRole_(j){j=String(j||'').trim().toUpperCase();if(j==='DIREKSI')return'direksi';if(j==='MANAGEMENT')return'management';if(j==='KOORDINATOR')return'koordinator';if(j==='ADMIN')return'admin';if(j==='DRIVER MANAGER'||j==='DRIVER MGR')return'driver_manager';if(j==='STAFF KONTER'||j==='PICKUP POINT')return'staff';return null}
function normalizeStaffHeader_(v){return String(v||'').trim().toLowerCase().replace(/\s+/g,' ')}function findStaffColumn_(h,n,f){var a=h.map(normalizeStaffHeader_);for(var i=0;i<n.length;i++){var x=a.indexOf(normalizeStaffHeader_(n[i]));if(x>=0)return x}return f}function getStaffSheetColumns_(h){return{email:findStaffColumn_(h,['Email'],0),nama:findStaffColumn_(h,['Nama'],1),gaji:findStaffColumn_(h,['Gaji Staff','Gaji'],2),idCabang:findStaffColumn_(h,['ID CABANG','ID Cabang'],3),staffId:findStaffColumn_(h,['ID Staff','Staff ID'],4),jabatan:findStaffColumn_(h,['Jabatan'],5),roleSistem:findStaffColumn_(h,['Role Sistem'],-1),phone:findStaffColumn_(h,['No WA Staff','No  WA Staff','No WA'],6),pin:findStaffColumn_(h,['Pin','PIN'],7),statusAktif:findStaffColumn_(h,['Status Aktif'],-1),syncStatus:findStaffColumn_(h,['Sync Status'],-1)}}
function resolveSystemRole_(raw,j){var x=String(raw||'').trim().toLowerCase();if(!x)return{role:mapJabatanToRole_(j),source:'jabatan'};return SYSTEM_ROLE_VALUES.indexOf(x)>=0?{role:x,source:'role_sistem'}:{role:null,source:'role_sistem_invalid',raw:x}}
function parseGajiSsot_(raw){if(raw===null||raw===undefined||raw==='')return null;if(typeof raw==='number')return isFinite(raw)?raw:null;var s=String(raw).replace(/rp/i,'').replace(/[.\s]/g,'').replace(/,/g,'.').trim(),n=parseFloat(s);return isFinite(n)&&n>=0?n:null}function normalizePin_(raw){var s=String(raw||'').trim();if(!s)return{valid:false,reason:'kosong'};if(!/^\d+$/.test(s))return{valid:false,reason:'bukan angka'};if(s.length<6)return{valid:false,reason:'terlalu pendek ('+s.length+' digit, min 6)'};return{valid:true,value:s}}
function parseStaffActive_(raw){if(raw===true||raw===1)return true;if(raw===false||raw===0)return false;if(raw===null||raw===undefined||raw==='')return null;var s=String(raw).trim().toUpperCase();if(['TRUE','AKTIF','ACTIVE','YA','YES','1'].indexOf(s)>=0)return true;if(['FALSE','NONAKTIF','INACTIVE','TIDAK','NO','0'].indexOf(s)>=0)return false;return null}
function kpiBranchMap_(){var rows=callSupabase('branches?select=id,slug')||[],m={};rows.forEach(function(r){if(r.slug)m[r.slug]=r.id});return m}
function _staffDedupeSource_(rows,profiles){
  var warnings=[],existingStaff={},existingEmail={};profiles.forEach(function(p){if(p.staff_id)existingStaff[p.staff_id]=p;if(p.email)existingEmail[String(p.email).trim().toLowerCase()]=p});
  var groupsStaff={};rows.forEach(function(r){(groupsStaff[r.staffId]||(groupsStaff[r.staffId]=[])).push(r)});var pass1=[];
  Object.keys(groupsStaff).forEach(function(k){var g=groupsStaff[k].sort(function(a,b){return a.rowNum-b.rowNum}),winner=g[0],ex=existingStaff[k];if(ex&&ex.email){var em=String(ex.email).trim().toLowerCase(),match=g.filter(function(r){return r.email===em});if(match.length)winner=match[0]}pass1.push(winner);g.forEach(function(r){if(r!==winner)warnings.push('CONFLICT staff_id '+k+': '+winner.email+' vs '+r.email+'; winner baris '+winner.rowNum+' berdasarkan existing identity/first-row; loser '+r.rowNum+' skip')})});
  var groupsEmail={};pass1.forEach(function(r){(groupsEmail[r.email]||(groupsEmail[r.email]=[])).push(r)});var result=[];
  Object.keys(groupsEmail).forEach(function(email){var g=groupsEmail[email].sort(function(a,b){return a.rowNum-b.rowNum}),winner=g[0],ex=existingEmail[email];if(ex&&ex.staff_id){var match=g.filter(function(r){return r.staffId===ex.staff_id});if(match.length)winner=match[0]}result.push(winner);g.forEach(function(r){if(r!==winner)warnings.push('CONFLICT email '+email+': '+winner.staffId+' vs '+r.staffId+'; winner '+winner.staffId+' baris '+winner.rowNum+'; loser '+r.staffId+' skip')})});
  result.sort(function(a,b){return a.rowNum-b.rowNum});return{rows:result,warnings:warnings}}
function _staffDedupePayload_(rows){var ids={},staff={},out=[],warnings=[];rows.forEach(function(r){if(ids[r.id]){warnings.push('Payload duplicate auth UUID '+r.id+' staff '+ids[r.id].staff_id+' vs '+r.staff_id+' — first wins');return}if(staff[r.staff_id]){warnings.push('Payload duplicate staff_id '+r.staff_id+' auth '+staff[r.staff_id].id+' vs '+r.id+' — first wins');return}ids[r.id]=r;staff[r.staff_id]=r;out.push(r)});return{rows:out,warnings:warnings}}
function syncStaffFromSSOT(){var t0=Date.now(),upserted=0,deactivated=0,skipped=0,errors=0,authNew=0,authCached=0,warnings=[];try{var sh=getMasterStaffSheet_(),values=sh.getDataRange().getValues();if(!values.length)throw new Error('MASTER DATA STAFF kosong');var cols=getStaffSheetColumns_(values[0]||[]);if(cols.statusAktif<0)throw new Error('Kolom Status Aktif tidak ditemukan — sync dibatalkan untuk mencegah reaktivasi salah');var branchMap=kpiBranchMap_(),now=new Date().toISOString(),raw=[];values.slice(1).forEach(function(row,i){var rowNum=i+2,idCabang=String(row[cols.idCabang]||'').trim();if(!idCabang||SKIP_CABANG_SYNC.indexOf(idCabang)>=0)return;var activeFlag=parseStaffActive_(row[cols.statusAktif]),syncStatus=cols.syncStatus>=0?String(row[cols.syncStatus]||'').trim():'';if(/CONFLICT/i.test(syncStatus))activeFlag=false;if(activeFlag===null){warnings.push('Baris '+rowNum+': Status Aktif kosong/tidak valid — skip aman');skipped++;return}if(!activeFlag){skipped++;return}var email=String(row[cols.email]||'').trim().toLowerCase(),nama=String(row[cols.nama]||'').trim(),staffId=String(row[cols.staffId]||'').trim(),roleResult=resolveSystemRole_(cols.roleSistem>=0?row[cols.roleSistem]:'',row[cols.jabatan]),phone=String(row[cols.phone]||'').trim()||null,gaji=parseGajiSsot_(row[cols.gaji]),branchId=branchMap[idCabang]||null,pin=normalizePin_(row[cols.pin]);if(!email||!nama||!staffId){warnings.push('Baris '+rowNum+': email/nama/staff_id kosong — skip');skipped++;return}if(!roleResult.role){warnings.push('Baris '+rowNum+' '+staffId+': role tidak valid — skip');skipped++;return}if(!pin.valid)warnings.push('Baris '+rowNum+' ('+staffId+' '+nama+'): legacy PIN '+pin.reason+' — Auth password tidak diubah; PIN RAOS tetap terpisah');if(!branchId&&idCabang!=='Head Office'&&idCabang!=='Admin')warnings.push('Baris '+rowNum+' '+staffId+': branch '+idCabang+' tidak ditemukan');raw.push({rowNum:rowNum,email:email,nama:nama,staffId:staffId,role:roleResult.role,phone:phone,gaji:gaji,branchId:branchId,pin:pin})});
  var allProfiles=callSupabase('user_profiles?select=id,staff_id,email,source,branch_id&limit=5000')||[],existing=allProfiles.filter(function(p){return p.source==='ssot_master_staff'}),ded=_staffDedupeSource_(raw,allProfiles);warnings=warnings.concat(ded.warnings);var valid=ded.rows,byStaff={},profileByAuth={};existing.forEach(function(p){if(p.staff_id)byStaff[p.staff_id]=p});allProfiles.forEach(function(p){profileByAuth[p.id]=p});var cached=[],newRows=[];valid.forEach(function(r){var ex=byStaff[r.staffId];if(ex){r.authId=ex.id;r.existingBranch=ex.branch_id;cached.push(r)}else newRows.push(r)});authCached=cached.length;
  if(newRows.length){var requests=newRows.map(function(r){var p={email:r.email,email_confirm:true,user_metadata:{full_name:r.nama,staff_id:r.staffId}};if(r.pin.valid)p.password=r.pin.value;return{url:CONFIG.SUPABASE_URL+'/auth/v1/admin/users',method:'post',contentType:'application/json',headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:'Bearer '+CONFIG.SUPABASE_KEY},payload:JSON.stringify(p),muteHttpExceptions:true}});for(var i=0;i<requests.length;i+=50){var br=newRows.slice(i,i+50),resp=UrlFetchApp.fetchAll(requests.slice(i,i+50));resp.forEach(function(res,j){var r=br[j],code=res.getResponseCode();if(code>=200&&code<300){try{r.authId=JSON.parse(res.getContentText()).id;authNew++}catch(e){errors++;warnings.push(r.staffId+' auth parse fail')}}else if(code===422||res.getContentText().indexOf('already')>=0){try{var id=callSupabase('rpc/get_auth_user_id_by_email','POST',{p_email:r.email});r.authId=Array.isArray(id)?id[0]:id;if(r.authId)authNew++}catch(e){errors++;warnings.push(r.staffId+' existing email lookup gagal')}}else{errors++;warnings.push('Baris '+r.rowNum+' '+r.staffId+' auth HTTP '+code)}})}}
  var payload=[];valid.forEach(function(r){if(!r.authId)return;var owner=profileByAuth[r.authId];if(owner&&owner.source!=='ssot_master_staff'){warnings.push('Baris '+r.rowNum+' '+r.staffId+': Auth UUID sudah dimiliki source='+owner.source+' staff_id='+owner.staff_id+' — tidak ditimpa');skipped++;return}if(owner&&owner.staff_id&&owner.staff_id!==r.staffId){warnings.push('Baris '+r.rowNum+' '+r.staffId+': Auth UUID terikat staff_id lain '+owner.staff_id+' — conflict, skip');skipped++;return}payload.push({id:r.authId,staff_id:r.staffId,email:r.email,full_name:r.nama,role:r.role,phone:r.phone,gaji:r.gaji,source:'ssot_master_staff',ssot_synced_at:now,is_active:true,is_geofence_exempt:isStaffGeofenceExempt_(r.nama),branch_id:r.existingBranch||r.branchId||null})});var pd=_staffDedupePayload_(payload);warnings=warnings.concat(pd.warnings);for(i=0;i<pd.rows.length;i+=400){var ch=pd.rows.slice(i,i+400);try{_staffBulkUpsert_(ch);upserted+=ch.length}catch(e){errors++;warnings.push('user_profiles bulk '+i+': '+e.message)}}
  var seen=valid.map(function(r){return r.staffId}),stale=existing.filter(function(p){return p.staff_id&&seen.indexOf(p.staff_id)<0}).map(function(p){return p.staff_id});for(i=0;i<stale.length;i+=100){var sl=stale.slice(i,i+100);try{callSupabase('user_profiles?staff_id=in.('+sl.map(encodeURIComponent).join(',')+')&source=eq.ssot_master_staff','PATCH',{is_active:false,ssot_synced_at:now});deactivated+=sl.length}catch(e){errors++;warnings.push('deactivate staff: '+e.message)}}warnings.slice(0,50).forEach(function(w){try{logSistem('warning','syncStaffFromSSOT','warning',w)}catch(_){}});var elapsed=((Date.now()-t0)/1000).toFixed(1),status=errors?'warning':(warnings.length?'warning':'success'),summary=upserted+' upsert, '+authNew+' auth baru, '+authCached+' auth cached, '+deactivated+' nonaktif, '+skipped+' skip, '+ded.warnings.length+' identity conflict, '+errors+' error, '+warnings.length+' warning, '+elapsed+'s';logSistem('sync','syncStaffFromSSOT',status,summary);return{upserted:upserted,authNew:authNew,authCached:authCached,deactivated:deactivated,skipped:skipped,identityConflicts:ded.warnings.length,errors:errors,warnings:warnings.length,warning_details:warnings.slice(0,20),elapsed_s:Number(elapsed)}}catch(e){try{logSistem('error','syncStaffFromSSOT','error',e.message||String(e))}catch(_){}throw e}}
function _staffBulkUpsert_(rows){var ids={},staff={};rows.forEach(function(r){if(ids[r.id])throw new Error('internal duplicate id '+r.id);if(staff[r.staff_id])throw new Error('internal duplicate staff_id '+r.staff_id);ids[r.id]=1;staff[r.staff_id]=1});var res=UrlFetchApp.fetch(CONFIG.SUPABASE_URL+'/rest/v1/user_profiles?on_conflict=id',{method:'POST',headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:'Bearer '+CONFIG.SUPABASE_KEY,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},payload:JSON.stringify(rows),muteHttpExceptions:true});if(res.getResponseCode()>=400)throw new Error('HTTP '+res.getResponseCode()+': '+res.getContentText().substring(0,500))}
function forceRefreshStaffAuth(){var t0=Date.now(),refreshed=0,skippedNoPin=0,skippedNoAuth=0,failed=0;var sh=getMasterStaffSheet_(),values=sh.getDataRange().getValues(),cols=getStaffSheetColumns_(values[0]||[]);if(cols.statusAktif<0)throw new Error('Kolom Status Aktif tidak ditemukan — forceRefresh dibatalkan');var profiles=callSupabase('user_profiles?source=eq.ssot_master_staff&select=id,staff_id&limit=1000')||[],auth={};profiles.forEach(function(p){if(p.staff_id)auth[p.staff_id]=p.id});var targets=[],seen={};values.slice(1).forEach(function(row){var activeFlag=parseStaffActive_(row[cols.statusAktif]),syncStatus=cols.syncStatus>=0?String(row[cols.syncStatus]||'').trim():'';if(/CONFLICT/i.test(syncStatus))activeFlag=false;if(activeFlag!==true)return;var staffId=String(row[cols.staffId]||'').trim(),pin=normalizePin_(row[cols.pin]);if(!staffId||seen[staffId])return;seen[staffId]=true;if(!pin.valid){skippedNoPin++;return}if(!auth[staffId]){skippedNoAuth++;return}targets.push({staffId:staffId,authId:auth[staffId],password:pin.value})});for(var i=0;i<targets.length;i+=50){var b=targets.slice(i,i+50),resp=UrlFetchApp.fetchAll(b.map(function(t){return{url:CONFIG.SUPABASE_URL+'/auth/v1/admin/users/'+t.authId,method:'put',contentType:'application/json',headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:'Bearer '+CONFIG.SUPABASE_KEY},payload:JSON.stringify({password:t.password}),muteHttpExceptions:true}}));resp.forEach(function(r,j){if(r.getResponseCode()>=200&&r.getResponseCode()<300)refreshed++;else{failed++;try{logSistem('recovery','forceRefreshStaffAuth','error',b[j].staffId+' HTTP '+r.getResponseCode())}catch(_){}}})}var elapsed=((Date.now()-t0)/1000).toFixed(1);logSistem('recovery','forceRefreshStaffAuth',failed?'warning':'success','refreshed='+refreshed+' skippedInvalidPin='+skippedNoPin+' skippedNoAuth='+skippedNoAuth+' failed='+failed+' '+elapsed+'s; RAOS PIN tidak diubah');return{refreshed:refreshed,skippedNoPin:skippedNoPin,skippedNoAuth:skippedNoAuth,failed:failed,errors:failed,elapsed_s:Number(elapsed)}}
