// ============================================================
// 19_raos_credentials_sync.gs — PIN RAOS dedicated credential sync V3
// LOCAL WORKING COPY. NO DEPLOY.
// ============================================================
function _raosCredNormHeader_(v){return String(v||'').trim().toLowerCase().replace(/\s+/g,' ')}
function _raosCredFindCol_(headers,names,fallback){var h=headers.map(_raosCredNormHeader_);for(var i=0;i<names.length;i++){var x=h.indexOf(_raosCredNormHeader_(names[i]));if(x>=0)return x}return fallback}
function _raosCredColumns_(headers){return {email:_raosCredFindCol_(headers,['Email'],0),raosPin:_raosCredFindCol_(headers,['RAOS PIN'],-1),raosId:_raosCredFindCol_(headers,['RAOS ID Staff','RAOS ID'],-1)}}
function _raosCredValidRaosPin_(v){return /^\d{4,12}$/.test(String(v||'').trim())}
function syncRaosCredentials(){var t0=Date.now(),updated=0,skipped=0,errors=0,warnings=[],conflicts=0;try{var sh=getMasterStaffSheet_(),values=sh.getDataRange().getValues();if(!values.length)throw new Error('MASTER DATA STAFF kosong');var cols=_raosCredColumns_(values[0]||[]);if(cols.raosPin<0)throw new Error('Kolom RAOS PIN belum ada. Tambahkan melalui menu admin yang existing.');var rows=values.slice(1),now=new Date().toISOString(),seenRaosId={},seenEmail={};
  rows.forEach(function(row,i){var rowNum=i+2,email=String(row[cols.email]||'').trim().toLowerCase(),raosPin=String(row[cols.raosPin]||'').trim(),raosCode=cols.raosId>=0?String(row[cols.raosId]||'').trim():'';if(!email||!raosPin){skipped++;return}if(!_raosCredValidRaosPin_(raosPin)){warnings.push('Baris '+rowNum+' ('+email+'): RAOS PIN wajib 4-12 digit angka — skip');skipped++;return}if(seenEmail[email]){conflicts++;warnings.push('Duplicate email '+email+' baris '+seenEmail[email]+' & '+rowNum+' — first row wins');skipped++;return}seenEmail[email]=rowNum;if(raosCode){var k=raosCode.toLowerCase();if(seenRaosId[k]){conflicts++;warnings.push('Duplicate RAOS ID '+raosCode+' baris '+seenRaosId[k]+' & '+rowNum+' — first row wins');skipped++;return}seenRaosId[k]=rowNum}
    try{var authResult=callSupabase('rpc/get_auth_user_id_by_email','POST',{p_email:email}),userId=Array.isArray(authResult)?authResult[0]:authResult;if(!userId){warnings.push('Baris '+rowNum+' ('+email+'): auth user belum ada — jalankan Sync Staff dulu');skipped++;return}_raosCredUpsert_({user_id:userId,raos_staff_code:raosCode||null,raos_pin:raosPin,updated_at:now});updated++;}catch(e){errors++;warnings.push('Baris '+rowNum+' ('+email+'): '+(e.message||e))}});
  warnings.slice(0,40).forEach(function(w){try{logSistem('sync','syncRaosCredentials','warning',w)}catch(_){}});var status=errors?'warning':(warnings.length?'warning':'success'),elapsed=((Date.now()-t0)/1000).toFixed(1),summary=updated+' upsert, '+skipped+' skip, '+conflicts+' conflict, '+errors+' error, '+warnings.length+' warning, '+elapsed+'s';logSistem('sync','syncRaosCredentials',status,summary);return {updated:updated,skipped:skipped,conflicts:conflicts,errors:errors,warnings:warnings.length,warning_details:warnings.slice(0,20),elapsed_s:Number(elapsed)};}catch(e){try{logSistem('sync','syncRaosCredentials','error',e.message||String(e))}catch(_){}throw e}}
function _raosCredUpsert_(row){var res=UrlFetchApp.fetch(CONFIG.SUPABASE_URL+'/rest/v1/raos_credentials?on_conflict=user_id',{method:'POST',headers:{apikey:CONFIG.SUPABASE_KEY,Authorization:'Bearer '+CONFIG.SUPABASE_KEY,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},payload:JSON.stringify(row),muteHttpExceptions:true});var code=res.getResponseCode();if(code>=400)throw new Error('Upsert HTTP '+code+': '+res.getContentText().substring(0,500))}
// menuSyncRaosCredentials existing dapat dipertahankan. P3 sync hanya owns RAOS ID/PIN.
// `ssot_pin` legacy tidak dibaca, tidak divalidasi, dan tidak ditulis oleh sync ini.
